### ISSUE TITLE
Icons don't support filling color

### ISSUE THREAD

**Issue by driesvints** [Faisal50x/blade-ionicons#2]
Hi there,

I'm opening this issue because we're currently working on integrating an icon search into the upcoming blade-ui-kit.com website. For this we need to be able to control the look and feel of the icons, especially its color.

It seems that this icon set doesn't supports filling its color yet. For this reason we've currently excluded your icon set from the search. It would be cool if you could fix this so your icon set can also be included in the global search.

### Details

[Here's an example](https://github.com/Faisal50x/blade-ionicons/blob/master/resources/svg/add-circle-outline.svg?short_path=392e185#L1) of your icon missing either `fill="none"  stroke="currentColor"` (outline icons) or `fill="currentColor"` (solid icons). 

### How to fix

Apply `fill="none"  stroke="currentColor"` to any outline icons ([Heroicons example](https://github.com/blade-ui-kit/blade-heroicons/blob/main/resources/svg/o-academic-cap.svg?short_path=c23120b#L1)) or `fill="currentColor"` to any solid icons ([Heroicons example](https://github.com/blade-ui-kit/blade-heroicons/blob/main/resources/svg/s-calculator.svg?short_path=7ad0b7e#L1)).

Also make sure you remove any attributes that don't belong on the icons like `id`, `class`, `width` & `height`, etc.

Please respond to this issue as soon as you've been able to fix this and tag a release and we'll include your library in the search.

**Comment by elliottregan** [comment]
I'm able to set the fill/stroke/etc by targeting the svg children (`<line>`, `<path>`) with CSS. 

For what it's worth, I always expect different icon packs to use different methods for styling. It would be great if they all used `currentColor` by default, but different artists have different concerns when making these packs, and they're always slightly different.

**Comment by swapnilsarwe** [comment]
@Foysal50x - i can address this once and for all. Also are you planning to maintain this repo?
Its not being updated since last 3 years. I can maintain it for you if you don't mind.

**Comment by Foysal50x** [comment]
> @Foysal50x - i can address this once and for all. Also are you planning to maintain this repo?
> Its not being updated since last 3 years. I can maintain it for you if you don't mind.


@swapnilsarwe I appreciate your willingness to maintain this project, as I am currently unable to dedicate the time needed for its upkeep. Your initiative is commendable, and I welcome your assistance with fixing the current issues and adding test cases. Once you have submitted a pull request, I will review it promptly and grant you maintainer permissions. Thank you for stepping up to support this project. Feel free to keep me informed of your progress.

**Comment by swapnilsarwe** [comment]
@Foysal50x 
i am maintaining a different package which I use to clean up SVGs while importing into blade-icons variant package of icon set. I have used that with a cleanup changes in `generation.php`.

PR: https://github.com/Foysal50x/blade-ionicons/pull/8

This PR also makes this icon set ready to be included on blade-ui-kit.com.

**Comment by Foysal50x** [comment]
Hey @driesvints, the issue is fixed!   Could you please add this icon to the Blade UI icon search?

Thanks to @swapnilsarwe for their support in making this happen!

**Comment by swapnilsarwe** [comment]
Have raised a PR already https://github.com/blade-ui-kit/blade-ui-kit.com/pull/167
