### ISSUE TITLE
PHP 8 & Composer 2 Support

### ISSUE THREAD

**Issue by gnarhard** [Faisal50x/blade-ionicons#3]
[InvalidArgumentException]                                   
  Package faisal50x/blade-ionicons has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

Running:
Composer version 2.0.8 2020-12-03 17:20:38
PHP 8.0.1 (cli) (built: Jan  8 2021 12:43:54) ( NTS )

**Comment by Foysal50x** [comment]
Add support for PHP 8


thank you
